name: "Build project"

on:
  push:

jobs:
  hello:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3
      - name: Build and push Docker images
        uses: docker/build-push-action@v3.2.0

